version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-snap"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-wasm-bundler"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "aleo"
    schedule:
      interval: "daily"
