version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-snap-wallet"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-snap-adapter"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-snap-ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "aleo-wasm-bundler"
    schedule:
      interval: "daily"
