name: Build web app

env:
  NODE_VERSION: "14.x"

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-web-app-build-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build-web-app:
    name: "Build web app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install latest stable Rust version
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web-app

      - name: Build web-app
        run: yarn run build
        working-directory: web-app
